#!/usr/bin/env python
" A script to check the length of the lines in the code"

__author__ = "Johan Hake (hake.dev@gmail.com)"
__copyright__ = "Copyright (C) 2010 " + __author__
__date__ = "2010-11-08 -- 2012-09-12"
__license__  = "GNU LGPL Version 3.0 or later"

from listfiles import list_python_files

max_line_length = 79
max_display_of_line = 50

clean = True

for f in list_python_files():
    too_long = {}
    for num, line in enumerate(open(f, "r").readlines()):
        if len(line) > max_line_length + 1:
            clean = False
            too_long[num] = line
    
    if too_long:
        print ""
        display = "In file: '%s':"%f
        print display
        print "-"*len(display)
        for num in sorted(too_long.keys()):
            print "%04d: %s"%(num+1, too_long[num][:max_display_of_line])

if clean:
    print "You are clean! Good job!"
