#!/usr/bin/env python
"A script that counts the number of code lines"

# Copyright (C) 2011-2012 Johan Hake
#
# This file is part of Gotran.
#
# Gotran is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Gotran is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Gotran. If not, see <http://www.gnu.org/licenses/>.

from listfiles import list_python_files

code_lines = 0
blank_lines = 0
comment_lines = 0
docstrings = 0
meta_data = 0

in_docstring = False

for f in list_python_files():
    for line in open(f, "r").readlines():
        line = line.strip()
        if in_docstring:
            docstrings += 1
            if line.endswith('"""'):
                in_docstring = False
        elif line.startswith('"""'):
            docstrings += 1
            in_docstring = True
        elif line.startswith('"'):
            docstrings += 1
        elif line.startswith("__"):
            meta_data += 1
        elif line.startswith("#"):
            comment_lines += 1
        elif len(line) == 0:
            blank_lines += 1
        else:
            code_lines += 1

print("### Gotran2 code statistics ###")
print("Code lines:      ", code_lines)
print("Meta data lines: ", meta_data)
print("Docstring lines: ", docstrings)
print("Blank lines:     ", blank_lines)
print("Comment lines:   ", comment_lines)
