#!/usr/bin/env python
" A script to check the length of the lines in the code"

__author__ = "Johan Hake (hake.dev@gmail.com)"
__copyright__ = "Copyright (C) 2010 " + __author__
__date__ = "2010-11-26 -- 2012-02-23"
__license__  = "GNU LGPL Version 3.0 or later"


from listfiles import list_files

for f in list_files():
    fixmes = {}
    for num, line in enumerate(open(f, "r").readlines()):
        if "FIXME" in line:
            fixmes[num] = line
    
    display = "In file: '%s':"%f
    if fixmes:
        print ""
        print display
        print "-"*len(display)
        for num in sorted(fixmes.keys()):
            print "%04d: %s"%(num+1, fixmes[num][:-1])

