#!/usr/bin/env python
" A script to check the length of the lines in the code"

__author__ = "Johan Hake (hake.dev@gmail.com)"
__copyright__ = "Copyright (C) 2010 " + __author__
__date__ = "2010-11-26 -- 2012-02-23"
__license__  = "GNU LGPL Version 3.0 or later"

from listfiles import list_files

for f in list_files():
    todos = {}
    for num, line in enumerate(open(f, "r").readlines()):
        if "NOTE" in line:
            todos[num] = line
    
    display = "In file: '%s':"%f
    if todos:
        print ""
        print display
        print "-"*len(display)
        for num in sorted(todos.keys()):
            print "%04d: %s"%(num+1, todos[num][:-1])

