#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright (C) 2012 Johan Hake
#
# This file is part of Gotran.
#
# Gotran is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Gotran is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Gotran. If not, see <http://www.gnu.org/licenses/>.

# System imports
import sys
import os

# gotran imports
from gotran2 import load_ode
from gotran2.common import error

def main(odefile, arguments, **kwargs):
    """
    Parse and generate code for the ode file
    """
    
    splitted_odefile = odefile.split(".")
    if len(splitted_odefile) > 1:
        if splitted_odefile[-1] in ["ode"]:
            odefile = ".".join(splitted_odefile[:-1])
    ode = load_ode(odefile)
    print "loaded ode just fine!"

if __name__ == "__main__":
    # FIXME: use argparse for this
    if len(sys.argv) == 1:
        error("pass more than 1 argument")
    if len(sys.argv) == 2:
        main(sys.argv[-1], None)
    else:
        error("not implemented")
    
