#!/usr/bin/env python

import os

from gotran.model.loadmodel2 import load_ode
from gotran.codegeneration.codegenerator2 import CppCodeGenerator
from gotran.common.options import parameters
from gotran.common import error

def main(filename, params):
    """
    Create a c header file from a gotran model
    """

    # Load Gotran model
    ode = load_ode(filename)

    # Create a C code generator
    gen = CppCodeGenerator(params)

    output = params.output

    if output:
        if not(len(output)>2 and output[-2:] == ".h"):
            output += ".h"
    else:
        output = filename.replace(".ode", "")+".h"

    f = open(output, "w")
    if params.system_headers:
        f.write("#include <cmath>\n")
        f.write("#include <cstring>\n")
        f.write("#include <stdexcept>\n")

    if params.class_code:
        f.write(gen.class_code(ode))
    else:
        f.write(gen.module_code(ode))

if __name__ == "__main__":
    import sys, os
    from modelparameters.parameterdict import *

    generation_params=parameters.generation.copy()
    
    params = ParameterDict(\
        output = Param("", description="Specify output file name"),\
        system_headers = Param(True, description="If true system "\
                               "headers needed to compile moudle is "\
                               "included."),\
        **generation_params)
    params.parse_args(usage="usage: %prog FILE [options]")#sys.argv[2:])
    
    if len(sys.argv) < 2:
        raise RuntimeError("Expected a single gotran file argument")

    if not os.path.isfile(sys.argv[1]):
        raise IOError("Expected the argument to be a file")
	 
    file_name = sys.argv[1]
    main(file_name, params)
