#!/usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = "Johan Hake (hake.dev@gmail.com)"
__copyright__ = "Copyright (C) 2012 " + __author__
__date__ = "2012-05-07 -- 2012-09-10"
__license__  = "GNU LGPL Version 3.0 or later"

# System imports
import sys
import os

# gotran imports
from gotran2 import load_ode
from gotran2.common import error

def main(odefile, arguments, **kwargs):
    """
    Parse and generate code for the ode file
    """
    
    splitted_odefile = odefile.split(".")
    if len(splitted_odefile) > 1:
        if splitted_odefile[-1] in ["ode"]:
            odefile = ".".join(splitted_odefile[:-1])
    ode = load_ode(odefile)
    print "loaded ode just fine!"

if __name__ == "__main__":
    # FIXME: use argparse for this
    if len(sys.argv) == 1:
        error("pass more than 1 argument")
    if len(sys.argv) == 2:
        main(sys.argv[-1], None)
    else:
        error("not implemented")
    
