#!/usr/bin/env python
# -*- coding: utf-8 -*-

__author__ = "Johan Hake (hake.dev@gmail.com)"
__date__ = "2013-05-07 -- 2013-05-07"
__copyright__ = "Copyright (C) 2013 " + __author__
__license__  = "GNU LGPL Version 3.0 or later"

from gotran import *

def main(filename, params):

    ode = load_ode(filename)

    print "Information of", ode.name, "Gotran model"
    if params.list_states:
        print "States:", ", ".join(state.name for state in ode.states)
    if params.list_parameters:
        print "Parameters:", ", ".join(param.name for param in ode.parameters)


if __name__ == "__main__":
    import sys, os
    from modelparameters.parameterdict import *
    
    params = ParameterDict(\
        list_states = Param(True, description="List states in model."),\
        list_parameters = Param(True, description="List states in model."),\
        )
    params.parse_args(usage="usage: %prog FILE [options]")
    
    if len(sys.argv) < 2:
        raise RuntimeError("Expected a single gotran file argument")

    if not os.path.isfile(sys.argv[1]):
        raise IOError("Expected the argument to be a file")
	 
    file_name = sys.argv[1]
    main(file_name, params)
